[tool.mypy]
strict = true
exclude = ["src/gen"]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = ["gen.*"]
ignore_errors = true

[tool.ruff]
line-length = 88
exclude = ["src/gen"]

[tool.ruff.lint]
select = ["E", "F", "I", "N", "W", "UP"]
ignore = ["E501"]
